name: Terraform CD
on: 
  workflow_dispatch:
    inputs:
      action:
        type: choice
        options: 
          - apply
          - destroy
        description: please select apply or destroy

      enviroment:
        type: choice
        options: 
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2  
        description: please type select environment

      

jobs: 
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.enviroment }}
    steps:
      - uses: actions/checkout@v7
        name: Checkout repository

      - name: Create tfvars file
        run: echo "${{ vars.TFVARS }}" > terraform.tfvars
        
      - name: Show tfvars content
        run: cat terraform.tfvars

      - name: Download Terraform
        uses: hashicorp/setup-terraform@v4


      - name: Secret key
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.enviroment }}

      

      - name: Terraform init
        run: terraform init  -input=false -backend-config=key=${{ inputs.enviroment }}/terraform.tfvars
        #because terraform init 1.loads plugins 2.initializes the backend S3

      - name: Terraform Apply or Destroy
        run: |
          if [[ ${{ inputs.action }} == "apply" ]]
          then
            terraform apply -input=false -auto-approve
          else
            terraform destroy -input=false -auto-approve
          fi